### ISSUE TITLE
odpscmd_public.zip cannot download

### ISSUE THREAD

**Issue by DallasRen** [aliyun/aliyun-odps-console#11]
Would you please help advise why I cannot download odpscmd_public.zip ? Thanks a lot.

**Comment by cornmonster** [comment]
Are you trying to download from this page? https://github.com/aliyun/aliyun-odps-console/releases

And could you please describe what happened when you download the file? The download did not start at all or it did not make any progress?

**Comment by DallasRen** [comment]
Yes I download from https://github.com/aliyun/aliyun-odps-console/releases.
The download did not have any progress, I checked the wireless have ni porblem but the download speed is 0kb/s, 0% download over 10 mins and finally failed.
